Get start state and metadata from Herdsman
srobo/sr-robot3-j5 pull request #14
Opened 2020-08-25 10:27 UTC by trickeydan

This should make the new API work with herdsman in it's current state.

The arguments on the CLI should also be compatible.

I have not be able to run herdsman myself. Perhaps @sersorrel could have a go.

I have been testing it as follows:

- Comment out line 65 in robot.py (No console support for ruggs)
- `mkfifo fifo`
- Run the following snippet:

```python
from sr.robot3 import *
from sr.robot3.env import *
r = Robot(env=CONSOLE_ENVIRONMENT, verbose=True)

print(r.mode)
print(r.zone)
print(r._arena)  # yeah it's private, to be used in vision
```
- `echo "{\"mode\": \"dev\", \"zone\": 0, \"arena\": 0}" > fifo`

Fixes #5

2020-08-25 10:28 UTC, trickeydan commented
Force pushed to rebase on master

2020-08-25 23:26 UTC, sersorrel requested changes
I currently don't have a working copy of the frontend, which means I can't properly test this – @raccube, did you get anywhere with that?

A minimally-altered herdsman can load a robot.zip with that code inside it, though, and the Robot object is constructed and waits for start. Pushing data down the FIFO that herdsman creates gets it past wait_start, and it loads the metadata happily (though see note about `data["arena"]`).

I'll draft a PR to herdsman with those changes soon™.

2020-08-25 23:26 UTC, sersorrel commented on sr/robot3/robot.py
> +                self._arena = str(data["mode"])
should this be `data["arena"]`, not `data["mode"]`? (if not: worth an explanatory comment?)

2020-08-25 23:26 UTC, sersorrel commented on sr/robot3/robot.py
> +                raise MetadataErrorException("Bad JSON data.") from e
can (the `repr` of) `raw_data` be included in the exception here?

2020-08-25 23:26 UTC, sersorrel commented on sr/robot3/robot.py
> +                    "Missing keys in metadata",
similarly, can (the `repr` of) `data` be included in the exception?

2020-08-25 23:26 UTC, sersorrel commented on sr/robot3/robot.py
> +                ) from None
why `from None`? it would probably be useful to know which key was missing, which the KeyError would include.

2020-08-26 01:33 UTC, sersorrel commented on sr/robot3/robot.py
> +                self._arena = str(data["mode"])
(looking a bit more carefully at the version of herdsman I've based my work on, if this _is_ going to change to `data["arena"]`, this will need a herdsman change)

2020-08-26 01:33 UTC, sersorrel commented
fyi, I've now made that herdsman PR: srobo/brain-herdsman#1

2020-08-26 08:54 UTC, raccube commented
@sersorrel I need to get a functioning robot system first

2020-10-08 18:02 UTC, trickeydan commented on sr/robot3/robot.py
> +                self._arena = str(data["mode"])
I've based this off https://github.com/srobo/brain-herdsman/blob/1b365826da1bf88b85d4eee47ceb9bd8c8e936c6/sr/herdsman/usercode.py#L199

What does your version want?

2020-10-15 13:05 UTC, trickeydan commented on sr/robot3/robot.py
> +                self._arena = str(data["mode"])
ping @sersorrel (in case you hadn't seen this)

2020-10-15 14:15 UTC, sersorrel approved these changes
lgtm

(might be nice to use a TypedDict for the loaded json `data` rather than Any, but honestly whatever)

2020-10-15 14:30 UTC, trickeydan commented
> lgtm
> 
> (might be nice to use a TypedDict for the loaded json `data` rather than Any, but honestly whatever)

Is there a backport of this to 3.6? I thought TypedDict was only available in 3.8+?

2020-10-15 15:15 UTC, sersorrel commented
looks like typing-extensions has a backport, but I'm not convinced it's worth the extra dependency

2020-10-15 15:19 UTC, trickeydan commented
> looks like [typing-extensions](https://pypi.org/project/typing-extensions/) has a backport, but I'm not convinced it's worth the extra dependency

Pretty certain we already depend on that for `Protocol` in [j5](https://github.com/j5api/j5/blob/42a094e39e85d593db3adee9d339d7b4c65c98d9/pyproject.toml#L25)

Not sure if it's in scope here.

2020-10-15 17:43 UTC, merged