Switch to April Vision
srobo/sr-robot3-j5 pull request #89
Opened 2022-12-17 20:16 UTC by WillB97

Switches vision system from Zoloto to April Vision.
Also adds handling for vision backends not being defined in an environment.

Temporarily sets the package version to 2023.1.1+april1

2022-12-17 21:22 UTC, trickeydan commented
I think this is probably dependent on review of the new library as well. Is there source published somewhere?

2022-12-20 18:54 UTC, WillB97 commented
The library source is at https://github.com/WillB97/april_vision

2023-01-03 19:28 UTC, trickeydan requested changes
Nice! 🎉 

Please see inline comments and strip and calibration strategy code as discussed :)

2023-01-03 19:28 UTC, trickeydan commented on pyproject.toml
> +version = "2023.1.1+april1"
```suggestion
version = "2023.1.0"
```

We shouldn't be bumping this in a feature PR. Please make a separate version release PR.

2023-01-03 19:28 UTC, trickeydan commented on sr/robot3/game.py
> +MARKER_SIZES: Dict[Iterable[int], int] = {
This should be a Collection. We can address this later though as you mentioned you have mypy issues.

2023-01-03 19:28 UTC, trickeydan commented on sr/robot3/vision/strategy.py
> +# ]
```suggestion
```

2023-01-03 20:04 UTC, trickeydan approved these changes

2023-01-03 20:17 UTC, trickeydan commented
Closes #74 
Closes #81

2023-01-03 22:23 UTC, merged